version: '2'
services:
    nginx-proxy:
        image: jwilder/nginx-proxy:latest
        container_name: nginx-proxy
        volumes:
            - /var/run/docker.sock:/tmp/docker.sock:ro
        ports:
            - 80:80
        restart: always

    sonarr:
        image: linuxserver/sonarr
        container_name: sonarr
        volumes:
            - /opt/media/config/sonarr:/config
            - /etc/localtime:/etc/localtime:ro
            - /opt/media/tv:/tv
            - /opt/media/download:/downloads
        ports:
            - 8989:8989
        env_file: uidgid.env
        environment:
            - VIRTUAL_HOST=sonarr.DOMAIN.home
            - VIRTUAL_PORT=8989
        restart: always

    radarr:
        image: linuxserver/radarr
        container_name: radarr
        volumes:
            - /opt/media/config/radarr:/config
            - /opt/media/movies:/movies
            - /opt/media/download:/downloads
            - /etc/localtime:/etc/localtime:ro
        ports:
            - 7878:7878
        env_file: uidgid.env
        environment:
            - VIRTUAL_HOST=radarr.DOMAIN.home
            - VIRTUAL_PORT=7878
        restart: always

    headphones:
        image: linuxserver/headphones
        container_name: headphones
        volumes:
            - /opt/media/config/headphones:/config
            - /opt/media/music:/music
            - /opt/media/download:/downloads
            - /etc/localtime:/etc/localtime:ro
        ports:
            - 8181:8181
        env_file: uidgid.env
        environment:
            - VIRTUAL_HOST=headphones.DOMAIN.home
            - VIRTUAL_PORT=8181
        restart: always

    ombi:
        image: linuxserver/ombi
        container_name: ombi
        volumes:
            - /opt/media/config/ombi:/config
            - /etc/localtime:/etc/localtime:ro
        ports:
            - 3579:3579
        env_file: uidgid.env
        environment:
            - VIRTUAL_HOST=ombi.DOMAIN.home
            - VIRTUAL_PORT=3579
        restart: always

    jackett:
        image: linuxserver/jackett
        container_name: jackett
        volumes:
            - /opt/media/config/jackett:/config
            - /opt/media/download/blackhole:/downloads
            - /etc/localtime:/etc/localtime:ro
        ports:
            - 9117:9117
        env_file: uidgid.env
        environment:
            - VIRTUAL_HOST=jackett.DOMAIN.home
            - VIRTUAL_PORT=9117
        restart: always

    nzbhydra:
        image: linuxserver/hydra
        container_name: nzbhydra
        volumes:
            - /opt/media/config/nzbhydra:/config
            - /opt/media/download:/downloads
            - /etc/localtime:/etc/localtime:ro
        ports:
            - 5075:5075
        env_file: uidgid.env
        environment:
            - VIRTUAL_HOST=nzbhydra.DOMAIN.home
            - VIRTUAL_PORT=5075
        restart: always

    muximux:
        image: linuxserver/muximux
        container_name: muximux
        volumes:
            - /opt/media/config/muximux:/config
            - /etc/localtime:/etc/localtime:ro
        env_file: uidgid.env
        environment:
            - VIRTUAL_HOST=muximux.DOMAIN.home
        restart: always

    nzbget:
        image: linuxserver/nzbget
        container_name: nzbget
        volumes:
            - /opt/media/config/nzbget:/config
            - /opt/media/download/completed:/complete
            - /opt/media/download:/downloads
        ports:
            - 6789:6789
        env_file: uidgid.env
        environment:
            - VIRTUAL_HOST=nzbget.DOMAIN.home
            - VIRTUAL_PORT=6789
        restart: always
